### PR TITLE
Extending the mongoId type to use exclude

### PR DESCRIPTION
**Pull request by sadasant**
:)

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  The changelog has not been updated. Please update the changelog.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  The version was not updated. Please update the version.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Your PR has lint warnings. Please consider fixing these.
      
<details>
  <summary>index.js</summary>
  <p>Full Path: <code>/home/circleci/project/src/index.js</code></p>
  
  <strong>'_' is assigned a value but never used.</strong>
  <code>Line 1: var _ = require('lodash/fp')</code>
</details>
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  The README has not been updated. Please update the README.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  We were able to automatically fix some formatting issues in this PR for you!
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by daedalus28** [comment]
Is this better than just wrapping in a `not` group?

**Comment by sadasant** [comment]
Doesn't hurt to have it, since we have it in the facet type.

**Comment by dshishkov** [comment]
I agree with @sadasant , it is not a bad addition and avoids creating another layer of nesting in the JSON structure sending the query since it has to be wrapped now in a group.type = not and we do support an exclusion mode in facet so why not here.

**Pull request merged**
