### PR TITLE
Add bool example type and change exists 

### PR DESCRIPTION
**Pull request by Akrion**
- Add bool example type with `falsy` support (which just does `$ne: true` on the field)
- Add tests for the bool example type

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>This PR has failing tests. Please alleviate the errors and commit them

</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 35ff02da10211f64c43d4efbbca86c9f74c1b85f


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f09d6539547e399cb0bbc2f37e1da4faad4031bf
</p>

**Comment by Akrion** [comment]
All tests run locally with no issues. Not sure what CI is talking about.

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fa1c6bdd0282046ddd32472920ae8356a24741cb
</p>

**Comment by daedalus28** [comment]
This looks great, just two things:

1. I think I'd expect it to always with falsey support as described here in #58. The contexture-elasticsearch node behaves that way implicitly as well because that's how es works, so I think we can just kill the flag and make it always behave that way.

2. We should consider some way for bool to not have a value. Right now, value is either truthy or falsey, which means that simply adding the filter affects search results. Bool and exists are the only filters that behave this way which makes it pretty unintuitive. We could either allow null/undefined to count against hasValue (so hasValue becomes _.isNil, a slight departure from the es version), or maybe add a flag (less elegant). The UI could be something like `[ ] Yes   [ ] No   [ ] Either` for `true/false/nil`

**Pull request merged**
